"""Index page generation — builds auto-maintained .md index files."""

from __future__ import annotations

from datetime import UTC, datetime


class IndexGenerator:
    def __init__(self, vault) -> None:
        self.vault = vault
        self.index_dir = vault.index_dir
        self.index_dir.mkdir(exist_ok=True)

    def build_all(self) -> list[str]:
        """Build all index pages. Cleans up stale pages first."""
        # Delete all existing index pages before regenerating
        if self.index_dir.exists():
            for old_file in self.index_dir.glob("*.md"):
                old_file.unlink()

        built = []
        built.append(self._build_master_index())
        built.append(self._build_tags_index())
        built.extend(self._build_per_tag_indexes())
        built.append(self._build_recent())
        built.append(self._build_orphans())
        built.append(self._build_stats())
        built.append(self._build_raw_pending())
        built.extend(self._build_by_month())
        built.append(self._build_stale())
        built.append(self._build_most_linked())
        return [b for b in built if b]

    def _write_index(self, filename: str, title: str, body: str) -> str:
        now_iso = datetime.now(UTC).isoformat()
        content = (
            f"---\n"
            f"title: \"{title}\"\n"
            f"id: \"{filename.replace('.md', '')}\"\n"
            f"type: index\n"
            f"created: {now_iso}\n"
            f"updated: {now_iso}\n"
            f"---\n\n"
            f"{body}\n\n"
            f"---\n*Auto-generated by bad-research. Do not edit manually.*\n"
        )
        path = self.index_dir / filename
        path.write_text(content, encoding="utf-8")
        return f"index/{filename}"

    def _build_master_index(self) -> str:
        rows = self.vault.db.execute(
            "SELECT id, title, path, status, type, parent, word_count, summary "
            "FROM notes WHERE type NOT IN ('index') ORDER BY parent, title"
        ).fetchall()

        lines = ["# Master Index\n", f"**{len(rows)}** notes in vault.\n"]

        # Group by parent
        groups: dict[str, list] = {}
        for r in rows:
            parent = r["parent"] or "Uncategorized"
            groups.setdefault(parent, []).append(r)

        for parent, notes in sorted(groups.items()):
            lines.append(f"\n## {parent}\n")
            for n in notes:
                status_badge = f"`{n['status']}`"
                summary = f" — {n['summary']}" if n["summary"] else ""
                lines.append(f"- [[{n['id']}]] — {n['title']}{summary} {status_badge} ({n['word_count']} words)")

        return self._write_index("_index.md", "Master Index", "\n".join(lines))

    def _build_tags_index(self) -> str:
        rows = self.vault.db.execute(
            "SELECT tag, COUNT(*) as count FROM tags GROUP BY tag ORDER BY count DESC"
        ).fetchall()

        lines = ["# Tags Index\n", f"**{len(rows)}** unique tags.\n"]
        for r in rows:
            # Only link to per-tag page if tag has 3+ notes (avoids index bloat)
            if r["count"] >= 3:
                lines.append(f"- **{r['tag']}** ({r['count']} notes) → [[_tag-{r['tag']}]]")
            else:
                lines.append(f"- **{r['tag']}** ({r['count']} notes)")

        return self._write_index("_tags.md", "Tags Index", "\n".join(lines))

    def _build_per_tag_indexes(self) -> list[str]:
        """Only generate per-tag index pages for tags with 3+ notes."""
        built = []
        tags = self.vault.db.execute(
            "SELECT tag, COUNT(*) as c FROM tags GROUP BY tag HAVING c >= 3 ORDER BY tag"
        ).fetchall()
        for tag_row in tags:
            tag = tag_row["tag"]
            rows = self.vault.db.execute(
                "SELECT n.id, n.title, n.status, n.word_count, n.summary "
                "FROM notes n JOIN tags t ON n.id = t.note_id "
                "WHERE t.tag = ? ORDER BY n.title",
                (tag,),
            ).fetchall()
            lines = [f"# Tag: {tag}\n", f"**{len(rows)}** notes.\n"]
            for r in rows:
                summary = f" — {r['summary']}" if r["summary"] else ""
                lines.append(f"- [[{r['id']}]] — {r['title']}{summary} `{r['status']}`")
            built.append(self._write_index(f"_tag-{tag}.md", f"Tag: {tag}", "\n".join(lines)))
        return built

    def _build_recent(self) -> str:
        rows = self.vault.db.execute(
            "SELECT id, title, status, type, created, updated, word_count "
            "FROM notes WHERE type NOT IN ('index') "
            "ORDER BY COALESCE(updated, created) DESC LIMIT 50"
        ).fetchall()

        lines = ["# Recently Updated\n"]
        for r in rows:
            date = r["updated"] or r["created"]
            if date and len(date) > 10:
                date = date[:10]
            lines.append(f"- `{date}` [[{r['id']}]] — {r['title']}")

        return self._write_index("_recent.md", "Recently Updated", "\n".join(lines))

    def _build_orphans(self) -> str:
        rows = self.vault.db.execute("""
            SELECT n.id, n.title, n.path, n.status
            FROM notes n
            WHERE n.type NOT IN ('index', 'raw')
              AND n.id NOT IN (SELECT DISTINCT target_id FROM links WHERE target_id IS NOT NULL)
              AND n.id NOT IN (SELECT DISTINCT source_id FROM links)
            ORDER BY n.title
        """).fetchall()

        lines = ["# Orphan Notes\n", f"**{len(rows)}** notes with no inbound or outbound links.\n"]
        if not rows:
            lines.append("*No orphans — all notes are connected!*")
        for r in rows:
            lines.append(f"- [[{r['id']}]] — {r['title']} ({r['path']})")

        return self._write_index("_orphans.md", "Orphan Notes", "\n".join(lines))

    def _build_stats(self) -> str:
        total = self.vault.db.execute("SELECT COUNT(*) as c FROM notes").fetchone()["c"]
        total_words = self.vault.db.execute(
            "SELECT COALESCE(SUM(word_count), 0) as c FROM notes"
        ).fetchone()["c"]
        total_links = self.vault.db.execute("SELECT COUNT(*) as c FROM links").fetchone()["c"]
        broken = self.vault.db.execute(
            "SELECT COUNT(*) as c FROM links WHERE target_id IS NULL"
        ).fetchone()["c"]
        total_tags = self.vault.db.execute(
            "SELECT COUNT(DISTINCT tag) as c FROM tags"
        ).fetchone()["c"]

        by_status = {}
        for r in self.vault.db.execute("SELECT status, COUNT(*) as c FROM notes GROUP BY status"):
            by_status[r["status"]] = r["c"]

        by_type = {}
        for r in self.vault.db.execute("SELECT type, COUNT(*) as c FROM notes GROUP BY type"):
            by_type[r["type"]] = r["c"]

        lines = [
            "# Vault Statistics\n",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Total notes | {total} |",
            f"| Total words | {total_words:,} |",
            f"| Unique tags | {total_tags} |",
            f"| Total links | {total_links} |",
            f"| Broken links | {broken} |",
            "",
            "## By Status\n",
        ]
        for s, c in sorted(by_status.items()):
            lines.append(f"- **{s}**: {c}")

        lines.append("\n## By Type\n")
        for t, c in sorted(by_type.items()):
            lines.append(f"- **{t}**: {c}")

        return self._write_index("_stats.md", "Vault Statistics", "\n".join(lines))

    def _build_raw_pending(self) -> str:
        rows = self.vault.db.execute(
            "SELECT id, title, path, created FROM notes WHERE type = 'raw' ORDER BY created DESC"
        ).fetchall()

        lines = ["# Unprocessed (Pending Compilation)\n", f"**{len(rows)}** raw notes awaiting compilation.\n"]
        for r in rows:
            date = r["created"][:10] if r["created"] and len(r["created"]) > 10 else r["created"]
            lines.append(f"- `{date}` [[{r['id']}]] — {r['title']}")

        return self._write_index("_raw-pending.md", "Raw Pending", "\n".join(lines))

    def _build_by_month(self) -> list[str]:
        """Generate per-month index pages for months with 3+ notes."""
        rows = self.vault.db.execute(
            "SELECT id, title, status, summary, created FROM notes "
            "WHERE type NOT IN ('index') AND created IS NOT NULL "
            "ORDER BY created DESC"
        ).fetchall()

        months: dict[str, list] = {}
        for r in rows:
            created = r["created"] or ""
            month = created[:7] if len(created) >= 7 else "unknown"
            months.setdefault(month, []).append(r)

        built = []
        for month, notes in sorted(months.items(), reverse=True):
            if len(notes) < 3 or month == "unknown":
                continue
            lines = [f"# Notes from {month}\n", f"**{len(notes)}** notes.\n"]
            for r in notes:
                date = (r["created"] or "")[:10]
                summary = f" — {r['summary']}" if r["summary"] else ""
                lines.append(f"- `{date}` [[{r['id']}]] — {r['title']}{summary}")
            built.append(self._write_index(f"_month-{month}.md", f"Month: {month}", "\n".join(lines)))
        return built

    def _build_stale(self) -> str:
        """Evergreen notes not updated in 6+ months — candidates for review."""
        from datetime import datetime, timedelta
        cutoff = (datetime.now(UTC) - timedelta(days=180)).isoformat()
        rows = self.vault.db.execute(
            "SELECT id, title, status, updated, created, word_count FROM notes "
            "WHERE status = 'evergreen' AND type NOT IN ('index') "
            "AND COALESCE(updated, created) < ? "
            "ORDER BY COALESCE(updated, created)",
            (cutoff,),
        ).fetchall()

        lines = ["# Stale Notes\n", f"**{len(rows)}** evergreen notes not updated in 6+ months.\n"]
        for r in rows:
            date = (r["updated"] or r["created"] or "")[:10]
            lines.append(f"- `{date}` [[{r['id']}]] — {r['title']} ({r['word_count']}w)")

        return self._write_index("_stale.md", "Stale Notes", "\n".join(lines))

    def _build_most_linked(self) -> str:
        """Top 30 notes by inbound link count."""
        rows = self.vault.db.execute(
            "SELECT l.target_id as id, n.title, COUNT(*) as inbound "
            "FROM links l JOIN notes n ON l.target_id = n.id "
            "WHERE l.target_id IS NOT NULL "
            "GROUP BY l.target_id ORDER BY inbound DESC LIMIT 30"
        ).fetchall()

        lines = ["# Most Linked Notes\n", f"Top {len(rows)} notes by inbound link count.\n"]
        for r in rows:
            lines.append(f"- [[{r['id']}]] — {r['title']} ({r['inbound']} inbound links)")

        return self._write_index("_most-linked.md", "Most Linked", "\n".join(lines))
